Add button cart
KaizeNodeLabs/SafeSwap pull request #66
Opened 2024-12-12 22:52 UTC by SimplementeCao

# 📝 Pull Request Title

## 🛠️ Issue
- Closes #60

## 📖 Description
- A shopping cart button needs to be added to the header for quick access to the cart and easier product review before checkout.

## ✅ Changes made
- Add the corresponding button and make sure it is responsive.

## 🖼️ Media (screenshots/videos)
-
![Screenshot from 2024-12-12 17-58-18](https://github.com/user-attachments/assets/aba85372-d623-439c-b335-abcaee4e4b78)

![Screenshot from 2024-12-12 17-57-25](https://github.com/user-attachments/assets/da51bc44-e225-4763-abf2-041df825a108)

## 📜 Additional Notes
-

2024-12-13 00:44 UTC, derianrddev commented
@SimplementeCao Good job! Just some minor comments. Please update the screenshot once you make the changes.

2024-12-13 00:49 UTC, derianrddev requested changes

2024-12-13 00:49 UTC, derianrddev commented on frontend/app/marketplace/page.tsx
> +				<Button size="lg" className="group">
On this button, remove the `size` property.

2024-12-13 00:49 UTC, derianrddev commented on frontend/app/marketplace/page.tsx
> +				<Button size="lg" className="group" onClick={() => router.push("/cart")}>
On this other button, also remove the `size` property and the `mr-2`.

2024-12-13 00:49 UTC, derianrddev commented
@SimplementeCao Good job! Just some minor comments. Please update the screenshot once you make the changes.

2024-12-13 01:00 UTC, SimplementeCao commented
@derianrddev Done! I have already modified the suggested changes and updated the images.

2024-12-13 01:18 UTC, derianrddev approved these changes

2024-12-14 01:10 UTC, danielcdz approved these changes
LGTM

2024-12-14 01:11 UTC, merged