feat: Remove the 'Connect Wallet' button from the Hero section
KaizeNodeLabs/SafeSwap pull request #68
Opened 2024-12-13 07:55 UTC by Jagadeeshftw

# 📝 Pull Request Title
- feat: Remove the 'Connect Wallet' button from the Hero section

## 🛠️ Issue
- Closes #58 

## 📖 Description
- This PR addresses issue #58 by removing the "Connect Wallet" button from the Hero section of the Landing Page. This change aligns with the updated design decision to move the "Connect Wallet" button to the header for better navigation and visibility. No changes were needed for the "Explore Marketplace" button, as it is already responsive and properly aligned.

## ✅ Changes made
- Removed the "Connect Wallet" button from the Hero section.
- Verified the responsiveness and alignment of the "Explore Marketplace" button.

## 🖼️ Media (screenshots/videos)
-
![image](https://github.com/user-attachments/assets/855e6fa3-d2bb-4060-924d-ab16184f2546)
-
![image](https://github.com/user-attachments/assets/5f0c24d9-db0f-46fc-95c9-45912baf03d2)

## 📜 Additional Notes
-

2024-12-13 08:09 UTC, Jagadeeshftw commented
Can you review this @danielcdz ?

2024-12-13 14:21 UTC, derianrddev requested changes

2024-12-13 14:21 UTC, derianrddev commented on frontend/app/components/ui/hero-section.tsx
>  						<Button variant="outline" size="lg" className="group">
On this button, remove the `variant` property, and from the icon, remove `dark:text-white`.

2024-12-13 14:21 UTC, derianrddev commented on frontend/app/components/ui/hero-section.tsx
> +}
Can you add a line at the end of the file?

2024-12-13 14:22 UTC, derianrddev commented
@Jagadeeshftw Good job! Just some minor comments. Please update the screenshot once you make the changes.

2024-12-14 05:09 UTC, Jagadeeshftw commented
@derianrddev your review comments were addressed and the screenshot was also updated.

2024-12-14 05:10 UTC, derianrddev approved these changes

2024-12-15 02:20 UTC, danielcdz approved these changes
LGTM! thanks for your work

2024-12-15 02:20 UTC, merged