feat"
KaizeNodeLabs/SafeSwap pull request #70
Opened 2024-12-13 20:58 UTC by johnnyzaet08

# 📝 Pull Request Title

## 🛠️ Issue
- Closes #issue-ID

## 📖 Description
- 

## ✅ Changes made
- 

## 🖼️ Media (screenshots/videos)
-

## 📜 Additional Notes
-

2024-12-14 18:15 UTC, derianrddev requested changes

2024-12-14 18:15 UTC, derianrddev commented on frontend/app/marketplace/page.tsx
> +						<DropdownMenuLabel>User Menu</DropdownMenuLabel>
Remove the `DropdownMenuLabel`

2024-12-14 18:15 UTC, derianrddev commented on frontend/app/marketplace/page.tsx
> +						<DropdownMenuSeparator/>
Remove the `DropdownMenuSeparator`

2024-12-14 18:18 UTC, derianrddev commented
@johnnyzaet08 Good job! Just some minor comments. Resolve the conflicts and add the user button to the new header, please.

2024-12-15 15:28 UTC, derianrddev approved these changes

2024-12-16 01:31 UTC, johnnyzaet08 commented
Hey @derianrddev, I need to wait for @danielcdz approval? Or can I do the merge right away? To solve the conflicts and make the merge.

2024-12-16 01:58 UTC, derianrddev commented
Hey @johnnyzaet08 , you can go ahead and do the merge right now. No problem.

2024-12-16 02:50 UTC, danielcdz commented
@johnnyzaet08 only maintainers can merge a PR! and this after receive at least 2 approvals on your PR

2024-12-16 04:29 UTC, johnnyzaet08 commented
Understood @danielcdz. 
Hey @derianrddev, I just did the update.  When I fixed the merge conflicts I got confused, then I realized and fixed it. Here is the test of the integration of the new button to the new header.

- Button integrated in the new header.
![Screenshot 2024-12-15 222600](https://github.com/user-attachments/assets/3e7c4292-e4b4-48a6-8bdf-ae14e76dac16)

2024-12-16 05:04 UTC, derianrddev commented
@johnnyzaet08 Thanks for the update, it looks good. We just need @danielcdz's approval to merge it into the project.

2024-12-16 19:11 UTC, danielcdz commented
@johnnyzaet08 one last update to fix the conflicts and then we can merge!

2024-12-16 19:11 UTC, danielcdz approved these changes

2024-12-16 19:40 UTC, merged