feat: Replace product card carousel with a single static image
KaizeNodeLabs/SafeSwap pull request #71
Opened 2024-12-14 00:47 UTC by Belloabraham121

# 📝 [Pull Request Title](feat: Replace product card carousel with a single static image)

## 🛠️ Issue
- Closes #issue-ID

## 📖 Description
- The current product cards use an image carousel, which can impact page loading times when there are many products and images. To improve performance and simplify the design, replace the carousel with a single static image for each card. Ensure the design remains visually appealing and responsive.

## ✅ Changes made
- Removed the image carousel from product card components.
- Displayed the first product image as a static image.
- Updated the design to ensure it aligns with the existing layout.
- Verified responsiveness and ensured proper behavior across different screen sizes.

## 🖼️ Media (screenshots/videos)
- Removed the carousel
![image](https://github.com/user-attachments/assets/e8c94796-b3b4-448d-8c92-9b05c5cda41b)

- Product card is still responsive 
![image](https://github.com/user-attachments/assets/3ac12673-e168-4627-923d-026eaae1bb64)

## 📜 Additional Notes
- While testing responsiveness, I observed that the Connect Wallet button is not responsive. This issue might need to be addressed separately.

2024-12-14 20:02 UTC, derianrddev requested changes

2024-12-14 20:02 UTC, derianrddev commented on frontend/app/components/ui/carousel.tsx
You can run the command `npx shadcn@latest add carousel` to restore the carousel component to its original state. This component will be needed later in the project, so it should not be modified.

2024-12-14 20:02 UTC, derianrddev commented on frontend/app/components/ui/image-carrousel.tsx
Leave this file as it was originally, for the same reason.

2024-12-14 20:03 UTC, derianrddev commented
@Belloabraham121 On the Marketplace page (`app/marketplace/page.tsx`), remove the `ImageCarousel` from the product cards and instead add an image for each product. That’s what I wanted.

2024-12-15 02:17 UTC, danielcdz commented
@Belloabraham121 let us know if you need any help or clarification

2024-12-16 13:08 UTC, Belloabraham121 commented
@derianrddev Kindly review

2024-12-16 15:24 UTC, derianrddev approved these changes

2024-12-16 19:08 UTC, danielcdz approved these changes
LGTM

2024-12-16 19:10 UTC, merged