Feat: delivery button
KaizeNodeLabs/SafeSwap pull request #77
Opened 2024-12-18 20:38 UTC by zleypner

# 📝 Add Delivery Location Button

## 🛠️ Issue
- Closes #64

## 📖 Description
This pull request implements the "Deliver to Costa Rica" button in the header. The button includes an icon and allows users to open a modal for selecting the delivery country. Currently, Costa Rica is the only option available, with its flag displayed in the selection modal. The design ensures responsiveness across different devices.

## ✅ Changes Made
- Added a "Deliver to Costa Rica" button in the header.
- Integrated a modal containing a select component based on `shadcn/ui`.
- Included the flag of Costa Rica in the select options.
- Ensured responsive design for both the button and modal.
- Incorporated the `Lucide React Icons` for the button.

## 🖼️ Media (Screenshots/Videos)

## 📜 Additional Notes
- The modal is designed to support future expansion for multiple delivery countries.
- Ensure consistent styling with the rest of the application.
- References:
  - [Lucide React Icons](https://lucide.dev/)
  - [shadcn/ui Select Component](https://ui.shadcn.dev/)

Please review the implementation and suggest any changes or improvements.

2024-12-18 20:39 UTC, zleypner commented
Hello @derianrddev!
🚧 **Work in Progress**: I am working on this issue and will update with implementation progress ASAP ⚡

2024-12-20 03:35 UTC, zleypner commented
Hello There! Almost done, just checking last details. 
![image](https://github.com/user-attachments/assets/97b98171-7de2-4ccb-bbdd-f4f5276bf8c9)

2024-12-20 04:52 UTC, derianrddev commented
@zleypner Great! Thanks for the update. Let me know if you need anything else to keep moving forward.

2024-12-20 15:40 UTC, danielcdz approved these changes

2024-12-21 03:53 UTC, zleypner commented
👋 Hello there! 🚩 The flag has been added. If there’s anything else I may help with, please let me know.  I’ll be glad to proceed with the updates! 

![image](https://github.com/user-attachments/assets/792b2bbe-a001-4787-b5a7-de1487a419b2)

2024-12-21 04:51 UTC, derianrddev requested changes
@zleypner  Good job!  Just some minor changes.

2024-12-21 04:51 UTC, derianrddev commented on frontend/app/components/header/Header.tsx
> +}
Add a line at the end of the file, please

2024-12-21 04:51 UTC, derianrddev commented on frontend/app/components/ui/delivery-button.tsx
Remove this file as it is unnecessary.

2024-12-21 04:51 UTC, derianrddev commented on frontend/app/components/ui/delivery-location-button.tsx
> +export default DeliveryLocationButton
Add a line at the end of the file, please

2024-12-21 07:55 UTC, zleypner commented
Hello @derianrddev ! I will proceed with the updates asap

2024-12-21 22:34 UTC, derianrddev approved these changes

2024-12-22 04:08 UTC, danielcdz approved these changes

2024-12-22 04:08 UTC, merged