Style/standardize productuploadmodal design
KaizeNodeLabs/SafeSwap pull request #78
Opened 2024-12-22 10:24 UTC by salazarsebas

# 📝 Pull Request Title
Standardize ProductUploadModal Design

## 🛠️ Issue
- Closes #59 

## 📖 Description
- This pull request adds the shadcn/ui components so that they can be used in the file as needed.
- The pull request also implements the shadcn/ui components in the file that was renamed as add-product-modal.

## ✅ Changes made
- The shadcn/ui components are added.
- Rename the file as add-product-modal.
- It adapts the shadcn/ui components to add-product-modal.

## 🖼️ Media (screenshots/videos)
- Video:
https://www.loom.com/share/7e49220be4e7434b89e907feebdea199?sid=a1de9267-941b-4329-89e7-b03522225b96

2024-12-22 14:52 UTC, derianrddev requested changes
@salazarsebas  Good job! Just some minor changes.

2024-12-22 14:52 UTC, derianrddev commented on frontend/app/components/ui/add-product-modal.tsx
> +interface ProductUploadModalProps {
Rename the interface to AddProductModalProps

2024-12-22 14:52 UTC, derianrddev commented on frontend/app/components/ui/add-product-modal.tsx
> +const ProductUploadModal: React.FC<ProductUploadModalProps> = ({
Rename the component to AddProductModal and here `React.FC<ProductUploadModalProps>` change it to   `React.FC<AddProductModalProps>`

2024-12-22 14:52 UTC, derianrddev commented on frontend/app/components/header/subheader/SubHeader.tsx
> +import AddProdcutModal from "../../ui/add-product-modal";
Rename `AddProdcutModal` to `AddProductModal`

2024-12-22 14:52 UTC, derianrddev commented on frontend/app/components/header/subheader/SubHeader.tsx
> +      <AddProdcutModal
Rename `AddProdcutModal` to `AddProductModal`

2024-12-22 14:52 UTC, derianrddev commented on frontend/app/components/ui/add-product-modal.tsx
> +export default ProductUploadModal;
Here also, rename to AddProductModal

2024-12-22 16:08 UTC, salazarsebas commented
Thank you very much for the corrections, I have already made them, can you confirm if everything is ok now?

2024-12-22 16:13 UTC, derianrddev approved these changes
@salazarsebas It looks good to me, we just need @danielcdz's approval to merge it.

2024-12-22 16:58 UTC, salazarsebas commented
> It looks good to me, we just need @danielcdz's approval to merge it.

Excellent, thank you very much. I remain attentive.

2024-12-22 22:20 UTC, danielcdz approved these changes
LGTM

2024-12-22 22:20 UTC, merged

2024-12-23 01:24 UTC, salazarsebas commented
> LGTM

tysm 🫡